name: actiondemo
on: workflow_dispatch
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: actiondemo
        uses: actions/checkout@v4
      - name: print index file
        run: cat index.html
        
